#!/bin/sh

auxilium() {
cat << EOF
-p para exportar domingo de pascua
-a para exportar ascension
-v para exportar viernes santo
-c para exportar martes de carnaval
-m para exportar a barca muxia
-y para asignar periodo de anos a exportar (por defecto es 10 años mas a partir del año actual)
EOF
}

[ -z "$1" ] && auxilium && exit

domingo_pascual() {
a=$(($anus%19))

b=$(($anus%4)) ; c=$(($anus%7))
k=$(($anus/100))

p=$(($((3+8*$k))/25))
q=$(($k/4))
m=$(($((15-$p+$k-q))%30))

n=$(($((4+$k-$q))%7))

d=$(($((19*$a+$m))%30))

e=$(($((2*$b+4*$c+6*$d+$n))%7))

[ $(($d+$e)) -lt 10 ] && fecha="$anus"03$(($d+$e+22))
[ $(($d+$e)) -ge 10 ] && fecha="$anus"04$(($d+$e-9))

[ $d -eq 28 ] && [ $e -eq 6 ] && [ $a -gt 10 ] && [ $fecha = "$anus"0425 ] \
	&& fecha="$anus"0418
[ $fecha = "$anus"0426 ] && fecha="$anus"0419
[ $(echo $fecha | wc -c) -le 8 ] \
	&& fecha=$(echo $fecha | sed 's/./&0/6')
echo $fecha
}


a_exporte=exporte.ics

id() {
rand="$(tr -dc A-Fa-f0-9 </dev/urandom | head -c 45 ; echo '')"
[ -f $a_exporte ] && while $(grep -w $rand exporte.ics); do
	rand="$(tr -dc A-Fa-f0-9 </dev/urandom | head -c 45 ; echo '')"
done
}

bloque () {
cat << EOF
BEGIN:VEVENT
DTSTART;VALUE=DATE:"$fecha"
DTEND;VALUE=DATE:"$(($fecha+1))"
DTSTAMP:"$fecha"T161541Z
UID:"$rand"
CREATED:"$fecha"T161522Z
DESCRIPTION:"$descripcion"
LAST-MODIFIED:20211122T161522Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:"$titulo"
TRANSP:TRANSPARENT
END:VEVENT
EOF
}

exportar() {
bloque |
        while IFS= read -r line; do
                echo "$line" | tr -d '"' >> $a_exporte
done
}

asignacion() {
printf 'nombre do evento: ' \
	&& read -r titulo
printf 'descripcion do evento: ' \
	&& read -r descripcion
}

derivado_pascua() {
	domingo_pascual >/dev/null
	[ -n "$fecha" ] && fecha=$(date -d ""$fecha" $dies" +%Y%m%d)
	echo $fecha
}
muxia() {
dom=$(for i in $(seq -w 01 30); do
	date -d ""$anus"09"$i"" '+%u %Y%m%d' | grep '^7'
done | cut -d' ' -f2 | sed -n '2p')

doma=$(for i in $(seq -w 01 30); do
	date -d ""$anus"09"$i"" '+%u %Y%m%d' | grep '^7'
done | cut -d' ' -f2 | sed -n '3p')
[ $(echo $dom | tail -c 3) -lt 9 ] && fecha=$doma || fecha=$dom
echo $fecha
}

[ -z $anus ] && anus=$(date +%Y)
limite=$(($anus+10))
loop() {
for i in $(seq $anus $limite); do
	$1
	id
	exportar
	anus=$(($i+1))
done
}

while getopts ":vpacmy" opt; do
        case "$opt" in
                y) anus=$OPTARG;;
                p) asignacion && loop domingo_pascual ;;
                v) dies="-2 days" && asignacion && loop derivado_pascua ;;
                c) dies="-47 days" && asignacion && loop derivado_pascua ;;
                a) dies="+39 days" && asignacion && loop derivado_pascua ;;
                m) asignacion && loop muxia ;;
                *) auxilium && exit;;
        esac
done
[ ! -f $a_exporte ] && exit
sed -i '/BEGIN:VCALENDAR/d' $a_exporte
sed -i '/END:VCALENDAR/d' $a_exporte

sed -i '1s/^/BEGIN:VCALENDAR\n/' $a_exporte
sed -i -e '$aEND:VCALENDAR' $a_exporte

